### ISSUE TITLE
[REQUEST] Increase meme cap

### ISSUE THREAD

**Issue by nabbylloydminsters** [DesktopGooseUnofficial/ResourceHub#10]
Is it possible to increase the cap for the memes the goose is able to get? (If there is one, at least...)

If that isn't possible, you could try and make it so the goose can pick from a certain range of memes.

**Comment by VukAnd** [comment]
I'm not sure if there even is a cap actually, I mean the 0.2 trailer said **unlimited** custom memes...

**Comment by nabbylloydminsters** [comment]
> I'm not sure if there even is a cap actually, I mean the 0.2 trailer said **unlimited** custom memes...

when i tried it with the vanilla goose, it would only choose ones from the top and not from the bottom. maybe just random chance?

**Comment by VukAnd** [comment]
Probably random chance yes, I'm not sure though

**Comment by SirGhosty22** [comment]
There seems to be a soft limit of 300 memes, will investigate further soon:tm:

**Comment by VukAnd** [comment]
+1

**Comment by VukAnd** [comment]
+1
