### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by snaildos** [DesktopGooseUnofficial/ResourceHub#110]
**Describe the mod you'd like**
We all know goose is a asshole, but, what if there is a mod that can ACTUALLY make it useful? 
Now we have voice talking to virtual assistance etc, but what about like, you can type things into a popupable text box, with commands to tell goose what to do, such as, open google chrome.
Maybe even chuck some AI to it, such as, how is your day?
I think it's simple to do (With all the current API's out there.)

**Describe alternatives you've considered**
I already disabled alot of gooses aggressive features, but I reckon we need him to help around.
(I do like the toy mod, it's just again, not useful. If I had this feature, I would use it WITH toy mod to have a little goose pet.)

**Additional context**
Nope. That's all :D

**Comment by hellogoose** [comment]
this would be an entire different thing
how add into goose?

**Comment by snaildos** [comment]
idk???
I want a goose that can be a assistant! 
Or ANYTHING that is like goose
that can muck around.
But, that doesn't exist.

**Comment by hellogoose** [comment]
https://medium.com/analytics-vidhya/create-your-own-desktop-pet-with-python-5b369be18868
add a window that pops up when a key is pressed and done, basically

**Comment by snaildos** [comment]
1) that's just rubbish and is nothing compared to goose.
2) it's too good. I'd like want goose to run around pulling out windows.
3) python is horrible.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snaildos** [comment]
Any ideas?

**Comment by hellogoose** [comment]
1: lmao okay?? don't see how the goose is too different
2. you can make it do that, make another window then make the window location around the "goose" window
3. [pick one here, that was just a reference](https://tkdocs.com/resources/languages.html)

**Comment by LilSizzurp** [comment]
>I think it's simple to do (With all the current API's out there.)

b u d d y
first of all that's not how coding works, you still need to **implement** the APIs which takes time.
second of all AI isn't as simple as just "heehoo i want it to do this for me" you need to actually TRAIN AI to make it functional.
third of all and finally; why would you want a useful goose?
