### ISSUE TITLE
I would like an option to change the goose to other things, such as a poro from league of legends/runeterra

### ISSUE THREAD

**Issue by GoosePoro** [DesktopGooseUnofficial/ResourceHub#111]
**Describe the mod you'd like**
This mod would just change the sprite of the goose to a poro, it walks similar to the goose.

**Describe alternatives you've considered**
An option to change the goose sprite to something else.
**Additional context**

![porobackground](https://user-images.githubusercontent.com/65372715/81992189-8a27f280-9608-11ea-8a4c-6a32fa53a9da.jpg)

**Comment by VukAnd** [comment]
the goose shape is hardcoded
