### ISSUE TITLE
getting a mod added to the list

### ISSUE THREAD

**Issue by Vortetty** [DesktopGooseUnofficial/ResourceHub#112]
i made a mod that makes the goose able to just like, not alive, how do i get it added to the list?

the mod is here: https://github.com/Vortetty/GooseExploder/

**Comment by VukAnd** [comment]
we require the source code to be available in your github repo

**Comment by Vortetty** [comment]
I will probably be doing a second release tiday after i figure out sysem.drawing ror explosion particles. Source will be posted then

**Comment by Vortetty** [comment]
@VukAnd the code is now in the repo
