### ISSUE TITLE
Desktop goose not showing up on other monitors

### ISSUE THREAD

**Issue by desantisg** [DesktopGooseUnofficial/ResourceHub#133]
The desktop goose does not show up on my two other monitors.

**Comment by PotNoodl** [comment]
This is intended as the current system the goose is running on would not be able to run it on multiple monitors

May I also add this is an officially recognised unofficial page, the creator of the goose has no control over this  so isn't  trhe place to ask that

This github repo is purely for community made mods not features baked into the goose
