### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by XxcatsxX** [DesktopGooseUnofficial/ResourceHub#139]
could some one please make a mod for desktop goose that makes the goose look like a cat. 
I love cats but can't find a good program for it
it would be very appreciated if some one could make it

thanks XxcatsxX

**Comment by ChrisChrome** [comment]
There's a cat desktop companion made by someone who goes by sea salt crackers
You can get it [here](https://sea-salt-crackers.itch.io/cat-companion)
Please note that this wasn't made by SamPerson, though he did say it's pretty cool ;)

Gonna close this one for now, if anyone wants to take this up and make a mod to turn the goose into a cat, feel free to re-open it

**Comment by XxcatsxX** [comment]
thanks
