### ISSUE TITLE
There are few links direct to 404

### ISSUE THREAD

**Issue by ChongWeiWei** [DesktopGooseUnofficial/ResourceHub#143]
After clicking Support Sam by giving him money via Patreon, How To Stop Desktop Goose and GamerBoi153’s Notepad Pack they show 404. Do not exist.

![image](https://user-images.githubusercontent.com/88237128/127744733-5fd03715-cd40-4cd3-9772-05c70d379d41.png)
![image](https://user-images.githubusercontent.com/88237128/127744751-5e7adb35-d02f-4c23-a0d5-54cf06fbf32e.png)
![image](https://user-images.githubusercontent.com/88237128/127744753-3946dfa1-6181-4f3d-aa8b-27cedbba0728.png)

**Comment by Vukkyy** [comment]
Fixed in #144.
