### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by moongazer07** [DesktopGooseUnofficial/ResourceHub#149]
whats stopping someone from decompiling the goose? And make it a virus? they can use things like ghidra etc so why make it closed source but not protect it from decompilers?
Tldr: someone decompiles the goose then they get the code just to add viruses to it

**Comment by Nicocelot** [comment]
The only solution is to download it from the offical source.

**Comment by Vukkyy** [comment]
Decompiling the goose is allowed as long as you don't share the source. I'm not the Desktop Goose developer, and that's not legal advice. You may want to join the official Discord server.
