### ISSUE TITLE
Submitting my mod

### ISSUE THREAD

**Issue by WackyModer** [DesktopGooseUnofficial/ResourceHub#151]
**Describe the mod you'd like**
I've created a mod that allows you to put the goose in "Jail".

**Describe alternatives you've considered**
As of now there is no mod that allows you to do this.

**Additional context**
This is the [**repository**](https://github.com/WackyModer/GooseJail) 

Here are some images of the mod
![image](https://user-images.githubusercontent.com/78763021/155012323-57cb654a-63bd-47b1-8428-2626b7347275.png)
![image](https://user-images.githubusercontent.com/78763021/155012324-88510f9f-e876-49d5-9ddd-054c9d7429c9.png)

**Comment by Vukkyy** [comment]
Using [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository), can you add the compiled DLL file of the mod to the repository?

**Comment by WackyModer** [comment]
Yes, I will do that. By the time you see this it will be up.
