### ISSUE TITLE
Hatgoos mod not available

### ISSUE THREAD

**Issue by SillySillyGoose** [DesktopGooseUnofficial/ResourceHub#189]
the link provided with the hatgoos mod page sends me to a discord attatchment that is no longer available

Link in question:
https://cdn.discordapp.com/attachments/676616674601992223/676952329110421517/HatGoos.zip

**Comment by nyakase** [comment]
Fixed in https://github.com/DesktopGooseUnofficial/ResourceHub/commit/06609d8019698a9f2b02aba9b9e79224a618d243
