### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by MotoAcidic** [DesktopGooseUnofficial/ResourceHub#37]
The team needs to get their discord under control and stop spamming everyone nonstop with the verify feature that was not needed at all.

**Comment by ChrisChrome** [comment]
The verification bot is there for a reason. We got raided, its under control now.

**Comment by VukAnd** [comment]
On top of this, submitting an issue here won't really help as most of us don't have any control over the server.

**Comment by Wuzado** [comment]
Hint: DesktopGoose*Unofficial*

**Comment by MotoAcidic** [comment]
Then why blast this on the official discord if it's unofficial. Seems counter intuitive since the owner and original developer isn't running the official repo to promote something that goes against what he requested in his current release.

> Link back to the itch page (on samperson.itch.io), or better yet, the YouTube video when that comes out.

With every release you are not doing this but just releasing files anyways and there is no file on your DesktopGooseUnofficial that gives the developer any credibility like he asked for.

**Comment by VukAnd** [comment]
There is a link on the front page, **right at the top**.
![image](https://user-images.githubusercontent.com/46850780/74313629-553fa180-4d74-11ea-8341-3f306f1fc42a.png)

Also would like to remind you that Sam himself is completely fine with us existing, he just says he wouldn't be a good manager of it and thus doesn't want "Official" stamped on it. 
(would send a screenshot, but it got lost in the raid)
