### ISSUE TITLE
Goose interacting with windows

### ISSUE THREAD

**Issue by ErrorNoInternet** [DesktopGooseUnofficial/ResourceHub#68]
Make the goose able to interact with windows on your screen. It could move them, minimize them (sometimes), or cover it in mud. 

Or you could make a mud bucket that the goose could drag anywhere on the screen and cover that area with mud. The goose just does like 4 things, so more actions/features would be better.

**Comment by jojos38** [comment]
Looked at it, seem too complicated and might cause a lot of issues

**Comment by LilSizzurp** [comment]
> Looked at it, seem too complicated and might cause a lot of issues
this is very much possible.

**Comment by jojos38** [comment]
> > Looked at it, seem too complicated and might cause a lot of issues
> 
> this is very much possible.

Yeah I tried to see what it would look like, it works with some window but not all, and cause bugs to some programs, also it doesn't work on full-screen windows and I'm sure I missed some bugs.. but with some fixing its possible indeed

**Comment by LilSizzurp** [comment]
> > > Looked at it, seem too complicated and might cause a lot of issues
> > 
> > 
> > this is very much possible.
> 
> Yeah I tried to see what it would look like, it works with some window but not all, and cause bugs to some programs, also it doesn't work on full-screen windows and I'm sure I missed some bugs.. but with some fixing its possible indeed

ok
