### ISSUE TITLE
Mod request: Add RainbowStrobe

### ISSUE THREAD

**Issue by AugieDog08** [DesktopGooseUnofficial/ResourceHub#86]
The RainbowStrobe mod. This isn't my mod, it's the default one that comes with the game. I just think that it should be added to the mod page in case someone accidentally deletes it. I'll attach the zip file or if you don't trust it you can add it yourself
[RainbowStrobe.zip](https://github.com/DesktopGooseUnofficial/ResourceHub/files/4340107/RainbowStrobe.zip)

**Comment by VukAnd** [comment]
I can add this to the Launcher if that's what you want?

**Comment by AugieDog08** [comment]
> I can add this to the Launcher if that's what you want?

Yes.  And also on this https://desktopgooseunofficial.github.io/ResourceHub/mods/explore/mods.html page.
