### ISSUE TITLE
An image isn't showing up on the main page

### ISSUE THREAD

**Issue by Wuzado** [DesktopGooseUnofficial/ResourceHub#90]
The "change config for the mods to work" GIF is properly showing up on the [repo/README page](https://github.com/DesktopGooseUnofficial/ResourceHub/), but it shows up an image from the address https://whitenamehate.group/5A6FEba.gif on the actual page, with the text "Image deleted at request of user". 

![The image we're speaking about](https://whitenamehate.group/5A6FEba.gif)

The domain https://whitenamehate.group/ seems to belong to an invite-only image hosting site https://mirage.photos , which holds a number of other domains.

I've tried force-reloading the site with CTRL-F5 and no extensions enabled, and even with a different browser (MS Edge), but it didn't help.

**Comment by LilSizzurp** [comment]
fuck sorry i accidentally removed that image
